# Generated by Django 4.2.5 on 2023-10-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'photos'},
        ),
    ]
