# Generated by Django 4.2.5 on 2023-10-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_photos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
