# Generated by Django 4.2.5 on 2023-10-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_photos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
